language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

install:
  - composer self-update
  - composer update

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR12 ./src/
  - ./vendor/bin/phpcs --standard=PSR12 ./test/

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
